version: 2.1

executors:
    docker:
        docker:
            -
                image: quay.io/twirphp/build
                environment:
                    GOFLAGS: -mod=readonly
                    CGO_ENABLED: "0"

commands:
    restore_go_module_cache:
        description: Restore Go module cache
        steps:
            -
                restore_cache:
                    name: Restore Go module cache
                    keys:
                        - gomod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                        - gomod-v1-{{ .Branch }}
                        - gomod-v1-master
                        - gomod-v1

    restore_php_dependencies:
        description: Restore PHP dependencies
        steps:
            -
                restore_cache:
                    name: Restore PHP dependencies
                    keys:
                        - composer-v1-{{ .Branch }}-{{ checksum "composer.json" }}
                        - composer-v1-{{ .Branch }}
                        - composer-v1-master
                        - composer-v1

jobs:
    gomodules:
        executor: docker

        steps:
            - checkout
            - restore_go_module_cache

            -
                run:
                    name: Download Go module cache
                    command: go mod download

            -
                save_cache:
                    name: Save Go module cache
                    key: gomod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                    paths:
                        - /go/pkg/mod

    composer:
        executor: docker

        steps:
            - checkout
            - restore_php_dependencies

            -
                run:
                    name: Install PHP dependencies
                    command: composer install

            -
                save_cache:
                    name: Save PHP dependencies
                    key: composer-v1-{{ .Branch }}-{{ checksum "composer.json" }}
                    paths:
                        - vendor
                        - composer.lock

    build:
        executor: docker

        steps:
            - checkout
            - restore_go_module_cache
            - restore_php_dependencies
            -
                run:
                    name: Test code generator
                    command: go test -v ./protoc-gen-twirp_php/...
            -
                run:
                    name: Test shared library
                    command: vendor/bin/phpunit -v
            -
                run:
                    name: Generate code
                    command: ./gen.sh
            -
                run:
                    name: Test generated code
                    command: vendor/bin/phpunit -v --group example
            -
                run:
                    name: Test client compatibility
                    command: clientcompat -client clientcompat/compat.sh
            -
                persist_to_workspace:
                    root: .
                    paths: .

    release:
        executor: docker

        steps:
            -
                attach_workspace:
                    at: .
            -
                deploy:
                    name: Release to Github
                    command: goreleaser --skip-validate

workflows:
    version: 2

    build:
        jobs:
            -
                gomodules:
                    filters:
                        tags:
                            only: /.*/
            -
                composer:
                    filters:
                        tags:
                            only: /.*/
            -
                build:
                    requires:
                        - gomodules
                        - composer
                    filters:
                        tags:
                            only: /.*/

            -
                release:
                    context: org-global
                    requires:
                        - build
                    filters:
                        branches:
                            ignore: /.*/
                        tags:
                            only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
